
version: '2'
services:
  discovery-service:
    image: kbsmanikanta/eureka:v1
    ports:
     - 8761:8761
    environment:
      - SPRING_PROFILES_ACTIVE=cloudlocal
      - JAVA_OPTS=-Xms64m -Xmx64m -Xss512k -Dfile.encoding=UTF8
  gateway:
    image: kbsmanikanta/zuul:v1
    ports:
      - 8765:8765
    environment:
      - SPRING_PROFILES_ACTIVE=cloudlocal
      - JAVA_OPTS=-Xms64m -Xmx64m -Xss512k -Dfile.encoding=UTF8
      - HOST_IP=10.0.2.15
