version: '3.0'

services:

  ms-a:
    image: kbsmanikanta/microservice-a:latest
    ports:
        - "9001:9001"

  ms-b:
    image: kbsmanikanta/microservice-b:latest
    ports:
        - "9002:9002"

  ms-c:
    image: kbsmanikanta/microservice-c:latest
    ports:
         - "9003:9003"
