kind: Service
apiVersion: v1
metadata:
  name: microservice-a
spec:
  selector:
    app: microservice-a
  ports:
  - protocol: TCP
    port: 9001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a
spec:
  selector:
      matchLabels:
        app: microservice-a
  strategy:
      type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-a
    spec:
      imagePullSecrets: 
        - name: registry
      serviceAccountName: default
      automountServiceAccountToken: true
      containers:
        - name: microservice-a
          image: docker.io/kbsmanikanta/microservice-a:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8087
          env: 
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace        
            - name: POD_NAME
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            - name: ROOT_LOG_PATH
              value: /tmp
            - name: CUSTOMER_LOG_PATH
              value: /tmp
            - name: ARCHIVE_LOG_PATH
              value: /tmp
            - name: SPRING_PROFILES_ACTIVE
              value: cloud,{{SPRING_PROFILE}}
            - name: JAVA_OPTS
              value: -Dcom.sun.management.jmxremote.local.only=false -Dfile.encoding=UTF8 -Djava.rmi.server.hostname=127.0.0.1 -Xms1024m -Xmx1024m -Xss1536k
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN           
          envFrom:
          - secretRef:
              name: microservice-a
